### ISSUE TITLE
Async Support

### ISSUE THREAD

**Issue by RobLoach** [james-work-account/is-ten-thousand#8]
This very important package needs async support.

**Comment by angel-carvajal-coder** [comment]
🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by james-work-account** [comment]
I'll look into it within 6-8 weeks.

**Comment by james-work-account** [comment]
@RobLoach I've worked night and day for the last few months to bring async support just for you. 🙇‍♂️

Usage:
```js
isTenThousand(10000, true) // set the shouldDoSomethingAsync flag to true
```
